version: '3'
services:
  ravendb:
    image: "ravendb/ravendb:ubuntu-latest"
    ports:
     - "8080:8080"
  nancytemplate:
    build: ./NancyApplication
    image: appname:nancytag
    ports:
     - "8081:80"
